# Generated by Django 4.2.7 on 2023-11-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='goal',
        ),
        migrations.AddField(
            model_name='habit',
            name='goals',
            field=models.ManyToManyField(blank=True, to='main_app.goal'),
        ),
    ]
