# Generated by Django 4.2.7 on 2023-11-21 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_goal_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletedGoal',
        ),
    ]
