# Generated by Django 4.2.7 on 2023-11-21 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_delete_completedgoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='tag',
        ),
    ]
