# Generated by Django 4.2.7 on 2023-11-22 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rename_frequency_habit_frequency_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='frequency_unit',
            new_name='frequency',
        ),
        migrations.AddField(
            model_name='habit',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='habit',
            name='goal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.goal'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
