# Generated by Django 4.2.7 on 2023-11-22 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_rename_frequency_unit_habit_frequency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='frequency',
            new_name='frequency_unit',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='last_updated_at',
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='habit',
            name='goal',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.goal'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
