# Generated by Django 4.2.7 on 2023-11-22 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_rename_frequency_unit_habit_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.goal'),
        ),
    ]
