# Generated by Django 4.2.7 on 2023-11-22 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_alter_habit_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='goal',
        ),
    ]
