# Generated by Django 4.2.7 on 2023-11-22 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_remove_habit_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='goal',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main_app.goal'),
        ),
    ]
