# Generated by Django 4.2.7 on 2023-11-23 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_habit_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='habit',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.goal'),
        ),
        migrations.DeleteModel(
            name='CompletedHabit',
        ),
    ]
