# Generated by Django 4.2.7 on 2023-11-23 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_habit_is_completed_alter_habit_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='goal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main_app.goal'),
        ),
    ]
